services:
  bitwarden-portal:
    image: bitwarden-portal
    build: .
    container_name: bitwarden-portal
    env_file: .env
    volumes:
      - ./backups:/app/backups
      - ./bitwarden-portal.sh:/app/backup.sh:ro
      - ./bw_match_items.py:/app/bw_match_items.py:ro
    restart: unless-stopped
